export const TOOGLE_DARKMODE = 'TOGGLE_DARKMODE'

export const FETCH_POSTS = 'FETCH_POSTS'
export const NEW_POST = 'NEW_POST'

// COVID-19
export const COVID_WORLD_TOTAL_STAT = 'COVID_WORLD_TOTAL_STAT'

export const COVID_COUNTRIES = 'COVID_COUNTRIES'
export const FETCH_COVID_COUNTRIES_BEGIN = 'FETCH_COVID_COUNTRIES_BEGIN'
export const FETCH_COVID_COUNTRIES_SUCCESS = 'FETCH_COVID_COUNTRIES_SUCCESS'
export const FETCH_COVID_COUNTRIES_FAILURE = 'FETCH_COVID_COUNTRIES_FAILURE'

export const COVID_COUNTRY = 'COVID_COUNTRY'

export const FETCH_COVID_COUNTRY_HISTORY_BEGIN =
  'FETCH_COVID_COUNTRY_HISTORY_BEGIN'
export const FETCH_COVID_COUNTRY_HISTORY_SUCCESS =
  'FETCH_COVID_COUNTRY_HISTORY_SUCCESS'
export const FETCH_COVID_COUNTRY_HISTORY_FAILURE =
  'FETCH_COVID_COUNTRY_HISTORY_FAILURE'

export const TRANSFORM_COUNTRY_HISTORY_DATA_FOR_GRAPH =
  'TRANSFORM_COUNTRY_HISTORY_DATA_FOR_GRAPH'

export const TRANSFORM_COUNTRIES_DATA_FOR_GRAPH =
  'TRANSFORM_COUNTRIES_DATA_FOR_GRAPH'
