export const TOOGLE_DARKMODE = 'TOGGLE_DARKMODE'

export const FETCH_POSTS = 'FETCH_POSTS'
export const NEW_POST = 'NEW_POST'

// COVID-19
export const COVID_WORLD_TOTAL_STAT = 'COVID_WORLD_TOTAL_STAT'
export const COVID_COUNTRIES = 'COVID_COUNTRIES'
export const COVID_COUNTRY = 'COVID_COUNTRY'
export const COVID_COUNTRY_HISTORY = 'COVID_COUNTRY_HISTORY'
